apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-dep
spec:
  template:
    spec:
      containers:
        - name: todo-backend
          env:
            - name: NATS_URL
              value: nats://my-nats.project.svc.cluster.local:4222
