apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pong
  template:
    metadata:
      labels:
        app: pong
    spec:
      containers:
        - name: pong
          image: joonasahovalli/pong:2.0.8
          env:
            - name: POSTGRES_DB
              value: pongdb
          envFrom:
            - secretRef:
                name: psql-credentials
