apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-dep
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: todos
  template:
    metadata:
      labels:
        app: todos
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: project-claim
      containers:
        - name: todos
          image: PROJECT/IMAGE_FRONTEND
          resources:
            requests:
              cpu: '100m'
              memory: '10Ki'
            limits:
              cpu: '200m'
              memory: '128Mi'
          volumeMounts:
            - name: shared-image
              mountPath: /usr/src/app/files
        - name: todo-backend
          image: PROJECT/IMAGE_BACKEND
          ports:
            - containerPort: 3001
          envFrom:
            - secretRef:
                name: psql-credentials
          resources:
            requests:
              cpu: '100m'
              memory: '10Ki'
            limits:
              cpu: '150m'
              memory: '64Mi'
