apiVersion: ENC[AES256_GCM,data:8pA=,iv:b8y2EYNttkHvm2rwkQKq2j5/ygWaRxPLl8liaH88HkI=,tag:zJP7KkYySFvtbiCfaYJrkQ==,type:str]
kind: ENC[AES256_GCM,data:tAHACj1D,iv:74P03mwzV6Ere+B24SuUbe7GZ3XwLXXRqA7W8zdNW50=,tag:0f2lNDLG9DZ37oCoSrMvkQ==,type:str]
metadata:
  name: ENC[AES256_GCM,data:2nA1q0D5WHfZkWlmfLmRpQ==,iv:bNROwmeSjP0WmQFEJfXZ9q/ognvg8OIG+HVrkpvvZYY=,tag:zSqhVFIi5kEiW/0bSS/k2Q==,type:str]
  namespace: ENC[AES256_GCM,data:znZhGj7iIw==,iv:0J+Z5+qnvnIlaBlilhlDrRj6BMPxsciTtKvv07n3D+4=,tag:2lSBVPwbDKDoRr4dJgzJgg==,type:str]
data:
  POSTGRES_USER: ENC[AES256_GCM,data:7CzLqSNS42a+umQ3smwQdQ==,iv:ka0Y9C8P7dWRESRRSwMaNo3MdEUyB3ceiPnIW1FSDQ0=,tag:3uJwbK7Qi2XxzLt+BJufIQ==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:jzxNrf5muQcxM6gslsUma6hH1Ogr/ZoGn6UVRA==,iv:BjNLqX5FeaUV9iX9xdCaU7nf5dZP10grfctD/L53ytY=,tag:ERctXVl/SbeDoLPchrW95g==,type:str]
  POSTGRES_DB: ENC[AES256_GCM,data:MJxRNzou7LsQBZk0,iv:6U/fpFa/ncE/VYLukaylu59NPaQoyIRZ26YmOC1tPUc=,tag:uOOMUa6SNBKMY1nj2VYxyw==,type:str]
  POSTGRES_HOST: ENC[AES256_GCM,data:KoHJ732KNhECcUyVNhU7bSv3MJ0=,iv:JcggHnVkmlT140boiqjqITbg3nLmPvwsc3HKt9rRmYU=,tag:hNy2quc0MhfGk4cNoWGd/A==,type:str]
  POSTGRES_PORT: ENC[AES256_GCM,data:SG4tMaIUamk=,iv:KOM3cDPq2paO3f3Va2aNPX10mqbgtQC8uXUmeMSIqZ0=,tag:+UuJT0/miuCJm14mqRMKjQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age12kq09s3sfnx4s8v26mrreuw5sej6mk3letjs96lze6c8nkcgyv8q27zkhk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXWW9mdUhKazkyTHYzSDU2
        N0E1R3J3cWJvLytvQ0lQc1JJZTdhZXg3bm5jCnVOb21naTdUYlNtRnFhSUdXcDMv
        SVQ5NnR0QjJuMTU4bGlyZDVhdEQ0cm8KLS0tIDFaN0hGamlsVTBEY2JiWk5DdVhr
        d1dxVWVIRTZGUk0wb3JwOVhkY0NLb0EK1nXYWaGKN6JhP0dYFdiqth8XGMF8lMPP
        Emph/Uq1SrMAlsQItzf6BUHZG+e9PDhDVBttmS4xGo16PSzxIDavzg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2025-01-12T13:34:52Z'
  mac: ENC[AES256_GCM,data:+y66qYe0izdWt1/eZBvLIAv+fPUvDjEvmPnMu8ZxgsGtTWhGl3a4j1KM/cx96OcsyszbmlFDs3frhxGXR/rZNkY3aaYpRj5T40e0E1sUS3y+6CVWhxW8p9kq4EE5QqE6DasG95RkiCaCK2ALA/ycPFMd5Q+j5ICsXfOj1aOa2Es=,iv:KwDyCEbM/UFqP+hGqMfM3ojTK4lKG567k2vojKBqVfs=,tag:XncP98AWCq3YxQzv5P3QFw==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.3
