apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcaster-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broadcaster
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: broadcaster
    spec:
      containers:
        - env:
            - name: NATS_URL
              value: PLACEHOLDER
            - name: PRODUCTION
              value: 'false'
          envFrom:
            - secretRef:
                name: webhook-secret
          image: PROJECT/IMAGE_BROADCASTER
          name: broadcaster
