apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logger
  template:
    metadata:
      labels:
        app: logger
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: exercise-claim
        - name: config-volume
          configMap:
            name: logger-configmap
      containers:
        - name: logs-writer
          image: LOGGER/IMAGE_WRITER
          volumeMounts:
            - name: shared-image
              mountPath: /usr/src/app/files
        - name: logs-reader
          image: LOGGER/IMAGE_READER
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /healthz
              port: 2341
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: logger-configmap
                  key: MESSAGE
          volumeMounts:
            - name: shared-image
              mountPath: /usr/src/app/files
            - name: config-volume
              mountPath: /usr/src/app/config
