apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: exercise-claim
  namespace: exercises
spec:
  storageClassName: exercise-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
