apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pong
  template:
    metadata:
      labels:
        app: pong
    spec:
      containers:
        - name: pong
          image: PONG/IMAGE_PONG
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /api
              port: 3001
          env:
            - name: POSTGRES_DB
              value: pongdb
          envFrom:
            - secretRef:
                name: psql-credentials
