apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging

resources:
- ./../../base

patchesStrategicMerge:
- staging-backend-patch.yaml
- staging-broadcaster-patch.yaml

images:
- name: PROJECT/IMAGE_BACKEND
  newName: joonasahovalli/todo-backend
  newTag: 6b5b4a7a99df5d01b178245aeb5a882441c9ec9a
- name: PROJECT/IMAGE_BROADCASTER
  newName: joonasahovalli/broadcaster
  newTag: 6b5b4a7a99df5d01b178245aeb5a882441c9ec9a
- name: PROJECT/IMAGE_FRONTEND
  newName: joonasahovalli/todos
  newTag: 6b5b4a7a99df5d01b178245aeb5a882441c9ec9a
