apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging

resources:
- ./../../base

patchesStrategicMerge:
- staging-backend-patch.yaml
- staging-broadcaster-patch.yaml

images:
- name: PROJECT/IMAGE_BACKEND
  newName: joonasahovalli/todo-backend
  newTag: 24a653acc5adad4a237261e317a54d0a3da11d8f
- name: PROJECT/IMAGE_BROADCASTER
  newName: joonasahovalli/broadcaster
  newTag: 24a653acc5adad4a237261e317a54d0a3da11d8f
- name: PROJECT/IMAGE_FRONTEND
  newName: joonasahovalli/todos
  newTag: 24a653acc5adad4a237261e317a54d0a3da11d8f
