apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging

resources:
  - ./../base

namePrefix: staging-

patches:
  - patch: |-
    apiVersion: v1
    kind: Namespace
    metadata:
      name: staging
