resources:
  - ./../../base

namePrefix: staging-

patches:
  - patch: |-
    apiVersion: v1
    kind: Namespace
    metadata:
      name: staging

namespace: staging

images:
  - name: PROJECT/IMAGE_BACKEND
    newName: joonasahovalli/todo-backend:2.1.2
  - name: PROJECT/IMAGE_FRONTEND
    newName: joonasahovalli/todos:2.0.5
  - name: PROJECT/IMAGE_BROADCASTER
    newName: joonasahovalli/broadcaster:1.1.0
