apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging

resources:
- ./../../base

patchesStrategicMerge:
- staging-backend-patch.yaml
- staging-broadcaster-patch.yaml

images:
- name: PROJECT/IMAGE_BACKEND
  newName: joonasahovalli/todo-backend
  newTag: fe266a84d1d3ce63f25f4d6d296f8e5be37f8ea6
- name: PROJECT/IMAGE_BROADCASTER
  newName: joonasahovalli/broadcaster
  newTag: fe266a84d1d3ce63f25f4d6d296f8e5be37f8ea6
- name: PROJECT/IMAGE_FRONTEND
  newName: joonasahovalli/todos
  newTag: fe266a84d1d3ce63f25f4d6d296f8e5be37f8ea6
