apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: todos-update-dep
spec:
  template:
    spec:
      containers:
        - name: PROJECT/IMAGE_BACKEND
          env:
            - name: NATS_URL
              value: nats://my-nats.production.svc.cluster.local:4222
