apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pong
  template:
    metadata:
      labels:
        app: pong
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: logger-claim
      containers:
        - name: pong
          image: joonasahovalli/pong:1.0.4
          volumeMounts:
            - name: shared-image
              mountPath: /usr/src/app/files
