apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project

images:
  - name: PROJECT/IMAGE_BACKEND
    newName: joonasahovalli/todo-backend:2.0.0
  - name: PROJECT/IMAGE_FRONTEND
    newName: joonasahovalli/todos:2.0.0

resources:
  - manifests/rollout.yaml
  - manifests/service.yaml
  - manifests/ingress.yaml
  - manifests/backendservice.yaml
  - manifests/projectstatefulset.yaml
  - manifests/cronjob.yaml
  - manifests/persistentvolumeclaim.yaml
  - manifests/secret.yaml
  - manifests/backupcronjob.yaml
  - manifests/analysistemplate.yaml
