apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project

images:
  - name: PROJECT/IMAGE_BACKEND
    newName: joonasahovalli/todo-backend:2.1.2
  - name: PROJECT/IMAGE_FRONTEND
    newName: joonasahovalli/todos:2.0.5
  - name: PROJECT/IMAGE_BROADCASTER
    newName: joonasahovalli/broadcaster:1.1.0

resources:
  # Deployments + templates
  - manifests/rollout.yaml
  - manifests/analysistemplate.yaml
  # Services + ingresses
  - manifests/service.yaml
  - manifests/backendservice.yaml
  - manifests/ingress.yaml
  # StatefulSets
  - manifests/projectstatefulset.yaml
  # CronJobs
  - manifests/cronjob.yaml
  # PersistentVolumeClaims
  - manifests/persistentvolumeclaim.yaml
  # Secrets
  - manifests/secret.yaml

  # Disabled for now
  # - manifests/broadcasterrollout.yaml
  # - manifestts/backupcronjob.yaml
  # - manifests/googlesecret.yaml
  # - manifests/webhooksecret.yaml
