apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki-serve-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiki-serve-app
  template:
    metadata:
      labels:
        app: wiki-serve-app

    spec:
      volumes:
        - name: wiki-serve-volume
          persistentVolumeClaim:
            claimName: wiki-serve-claim

      initContainers:
        - name: init-container
          image: joonasahovalli/init:1.1.0
          volumeMounts:
            - mountPath: /usr/tmp/www
              name: wiki-serve-volume
        - name: sidecar-container
          image: joonasahovalli/side:1.1.1
          restartPolicy: Always
          volumeMounts:
            - mountPath: /usr/tmp/www
              name: wiki-serve-volume

      containers:
        - name: nginx-container
          image: joonasahovalli/wikiserve:1.0.0
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/tmp/www
              name: wiki-serve-volume
---
apiVersion: v1
kind: Service
metadata:
  name: wiki-serve-svc
spec:
  type: NodePort
  selector:
    app: wiki-serve-app
  ports:
    - name: http
      nodePort: 30080
      protocol: TCP
      port: 1234
      targetPort: 80
