apiVersion: v1
kind: PersistentVolume
metadata:
  name: wiki-serve-pv
spec:
  storageClassName: wiki-serve-pv
  capacity:
    storage: 50Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  local:
    path: /tmp/kube
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3d-k3s-default-agent-0
