apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: PROJECT/IMAGE_BACKEND
    newName: joonasahovalli/todo-backend
  - name: PROJECT/IMAGE_FRONTEND
    newName: joonasahovalli/todos

resources:
  - manifests/deployment.yaml
  - manifests/service.yaml
  - manifests/ingress.yaml
  - manifests/backendservice.yaml
  - manifests/projectstatefulset.yaml
  - manifests/cronjob.yaml
  - manifests/persistentvolumeclaim.yaml
  - manifests/secret.yaml
  - manifests/backupcronjob.yaml
  - manifests/googlesecret.yaml
