apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# For ex. 4.07
namespace: exercises

images:
- name: LOGGER/IMAGE_READER
  newName: joonasahovalli/logs-reader
  newTag: e589ce8cae4e5e53ed53fc47b9755eeace640f8e
- name: LOGGER/IMAGE_WRITER
  newName: joonasahovalli/logs-writer
  newTag: e589ce8cae4e5e53ed53fc47b9755eeace640f8e
- name: PONG/IMAGE_PONG
  newName: joonasahovalli/pong
  newTag: e589ce8cae4e5e53ed53fc47b9755eeace640f8e

  # Pong

  # Logger

  # Ingress

  # Volumes
resources:
- ./pong/manifests/deployment.yaml
- ./pong/manifests/service.yaml
- ./pong/manifests/statefulset.yaml
- ./logger/manifests/deployment.yaml
- ./logger/manifests/service.yaml
- ./logger/manifests/persistentvolumeclaim.yaml
- ./logger/manifests/configmap.yaml
- ./ingress/ingress.yaml
- ./volumes/persistentvolume.yaml
