apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production

resources:
  - ./../base

namePrefix: prod-

patches:
  - patch: |-
    apiVersion: v1
    kind: Namespace
    metadata:
      name: production
