apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: broadcaster-rollout
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broadcaster
  strategy:
    canary:
      steps:
        - setWeight: 50
        - analysis:
            templates:
              - templateName: project-cpu-rate
        - pause:
            duration: 20s
  template:
    metadata:
      labels:
        app: broadcaster

    spec:
      containers:
        - name: broadcaster
          image: PROJECT/IMAGE_BROADCASTER
          envFrom:
            - secretRef:
                name: webhook-secret
          env:
            - name: NATS_URL
              value: nats://my-nats.project.svc.cluster.local:4222
