name: Build and publish application

on:
  push:

defaults:
  run:
    working-directory: part4/

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build images
        run: |-
          docker build -t "joonasahovalli/pong:$GITHUB_SHA" ./pong
          docker build -t "joonasahovalli/logs-reader:$GITHUB_SHA" ./logger/logs-reader
          docker build -t "joonasahovalli/logs-writer:$GITHUB_SHA" ./logger/logs-writer

      - name: Publish images
        run: |-
          docker push "joonasahovalli/pong:$GITHUB_SHA"
          docker push "joonasahovalli/logs-reader:$GITHUB_SHA"
          docker push "joonasahovalli/logs-writer:$GITHUB_SHA"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2.1.0

      - name: Set kustomize images
        run: |-
          kustomize edit set image PONG/IMAGE_PONG=joonasahovalli/pong:$GITHUB_SHA
          kustomize edit set image LOGGER/IMAGE_READER=joonasahovalli/logs-reader:$GITHUB_SHA
          kustomize edit set image LOGGER/IMAGE_WRITER=joonasahovalli/logs-writer:$GITHUB_SHA

      - name: commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: 'part4/kustomization.yaml'
          message: New version released ${{ github.sha }}
