name: Build and publish application

on:
  push:
    branches:
      - main
    tags:
      - '*'

defaults:
  run:
    working-directory: part4/project/base

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build images
        run: |-
          docker build -t "joonasahovalli/todo-backend:$GITHUB_SHA" ./../backend
          docker build -t "joonasahovalli/todos:$GITHUB_SHA" ./../todos
          docker build -t "joonasahovalli/broadcaster:$GITHUB_SHA" ./../broadcaster

      - name: Publish images
        run: |-
          docker push "joonasahovalli/todo-backend:$GITHUB_SHA"
          docker push "joonasahovalli/todos:$GITHUB_SHA"
          docker push "joonasahovalli/broadcaster:$GITHUB_SHA"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2.1.0

      - name: Determine if should deploy in prod or staging
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "ENV=prod" >> $GITHUB_ENV
          else
            echo "ENV=staging" >> $GITHUB_ENV
          fi

      - name: Create temporary branch to combat detached HEAD
        run: |
          git checkout -B temp

      - name: Set kustomize images
        run: |-
          if [ "$ENV" == "prod" ]; then

          cd ./../overlays/production

          else

          cd ./../overlays/staging

          fi

          kustomize edit set image PROJECT/IMAGE_BACKEND=joonasahovalli/todo-backend:$GITHUB_SHA
          kustomize edit set image PROJECT/IMAGE_FRONTEND=joonasahovalli/todos:$GITHUB_SHA
          kustomize edit set image PROJECT/IMAGE_BROADCASTER=joonasahovalli/broadcaster:$GITHUB_SHA

      - name: commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: 'part4/project/**/kustomization.yaml'
          message: New version released ${{ github.sha }}

      - name: Push changes
        run: |
          git push origin temp:main

      - name: Delete temporary branch
        run: |
          git push origin --delete temp
