name: Build and publish application

on:
  push:

defaults:
  run:
    working-directory: part4/project/base

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build images
        run: |-
          docker build -t "joonasahovalli/todo-backend:$GITHUB_SHA" ./../backend
          docker build -t "joonasahovalli/todos:$GITHUB_SHA" ./../todos
          docker build -t "joonasahovalli/broadcaster:$GITHUB_SHA" ./../broadcaster

      - name: Publish images
        run: |-
          docker push "joonasahovalli/todo-backend:$GITHUB_SHA"
          docker push "joonasahovalli/todos:$GITHUB_SHA"
          docker push "joonasahovalli/broadcaster:$GITHUB_SHA"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2.1.0

      - name: Set kustomize images
        run: |-
          kustomize edit set image PROJECT/IMAGE_BACKEND=joonasahovalli/todo-backend:$GITHUB_SHA
          kustomize edit set image PROJECT/IMAGE_FRONTEND=joonasahovalli/todos:$GITHUB_SHA
          kustomize edit set image PROJECT/IMAGE_BROADCASTER=joonasahovalli/broadcaster:$GITHUB_SHA

      - name: commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: 'part4/project/base/kustomization.yaml'
          message: New version released ${{ github.sha }}
